### ISSUE TITLE
Image alignments wide and full gone with PBF 2.8.6

### ISSUE THREAD

**Issue by luminuu** [MapSteps/Page-Builder-Framework#41]
I guess this issue is caused by changes made regarding issue #40. When working with images, in version 2.8.6 the alignments for wide and full width are gone. I tested the image and the cover block, but I assume this happens at other blocks as well, where these were previously available. All happens with WP 5.9.

Here's the image alignment select in 2.8.4/2.8.5:
![grafik](https://user-images.githubusercontent.com/7585600/151851327-da641cd4-7658-49fc-a817-adb0d646c56f.png)

The same image with 2.8.6:
![grafik](https://user-images.githubusercontent.com/7585600/151851856-e3f3feca-4b9d-4bcc-8f40-47c31484f7e5.png)

I think it's caused as there are no other settings set in the theme.json file and apparently many options are now gone when they are not activated. I have not looked into this yet myself, I just wanted to drop the issue here, I can have a look at it tomorrow too.

**Comment by mapsteps** [comment]
Something must have changed with the addition of the theme.json. I had to also implement a fix because all items inside Gutenberg were suddenly full-width. Reference - https://github.com/MapSteps/Page-Builder-Framework/commit/e4f53e54b746ba1b00ccc1262677c52e2ab9fd4a

Maybe we're missing something in the theme.json that would handle that? I'm going to have another look.
